version: '3'

networks:
    crgroups-portal-network:

services:
    crgroups-portal-nginx:
        build:
            context: ./nginx/
            target: dev
        tty: true
        environment:
            PHP_FPM_HOST: crgroups-portal-php:9000
        volumes:
            - ./:/var/www/
            - ./nginx/templates:/etc/nginx/templates
        networks:
            - crgroups-portal-network
        ports:
            - 3000:80
    crgroups-portal-php:
        build:
            context: ./
            target: dev
        tty: true
        environment: 
            DEVELOPMENT: ${DEVELOPMENT}
            MYSQL_CONN_STRING: ${MYSQL_CONN_STRING}
        volumes:
            - ./:/var/www/
        networks:
            - crgroups-portal-network

