-- Post import - Alter tables to handle the DATE_SUBMITTED changes
	
    ALTER TABLE SMALL_GROUPS 
    CHANGE COLUMN `DATE_SUBMITTED` `DATE_SUBMITTED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL ;
		
-- Set valid values for DATE_SUBMITTED
	
    UPDATE SMALL_GROUPS SET DATE_SUBMITTED = '2020-01-01 12:00:00' WHERE DATE_SUBMITTED < '2020-01-01 00:00:00'; 
		
-- Delete unused fields
	
    ALTER TABLE SMALL_GROUPS 
    DROP COLUMN `OWNER`,
    DROP COLUMN `IP_ADDRESS`,
    DROP COLUMN `PREVIOUS_LEADERSHIP`,
    DROP COLUMN `CO_LEADER_PREVIOUS_LEADERSHIP`,
    DROP COLUMN `AUTHOR`;